# Generated by Django 4.0.3 on 2022-06-13 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Monument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(blank=True, max_length=500, null=True)),
                ('data_more_info', models.CharField(blank=True, max_length=500, null=True)),
                ('nome', models.CharField(blank=True, max_length=500, null=True)),
                ('genero', models.CharField(blank=True, max_length=500, null=True)),
                ('etinia', models.CharField(blank=True, max_length=500, null=True)),
                ('endereco', models.CharField(blank=True, max_length=500, null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('long', models.FloatField(blank=True, null=True)),
                ('tombado', models.CharField(blank=True, max_length=500, null=True)),
                ('link', models.CharField(blank=True, max_length=500, null=True)),
                ('iphan', models.CharField(blank=True, max_length=500, null=True)),
                ('fonte', models.CharField(blank=True, max_length=500, null=True)),
                ('tipo', models.CharField(blank=True, max_length=500, null=True)),
                ('material', models.CharField(blank=True, max_length=500, null=True)),
                ('condeph', models.CharField(blank=True, max_length=500, null=True)),
                ('conpres', models.CharField(blank=True, max_length=500, null=True)),
                ('autor', models.CharField(blank=True, max_length=500, null=True)),
                ('endereco_original', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'ordering': ['data'],
            },
        ),
    ]
