# Generated by Django 4.0.3 on 2022-06-20 19:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('spmap', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='monument',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='monuments', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
